name: projeto_criptos
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  fl_chart: ^0.55.1
  decimal: ^2.3.0
  dio: ^4.0.6
  auto_size_text: ^3.0.0
  json_annotation: ^4.7.0
  loading_animation_widget: ^1.2.0+3
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  build_runner: ^2.2.1
  json_serializable: ^6.4.0
  faker: ^2.0.0
  network_image_mock: ^2.1.1
  
  
  
  
  
  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  generate: false
  
  
  
  

  
  

  
  

  
  
  
  
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets\fonts\Montserrat-Bold.ttf
        - asset: assets\fonts\Montserrat-Regular.ttf
    
  
  
